### ISSUE TITLE
TODO - 

### ISSUE THREAD

**Issue by thisisnic** [thisisnic/arrowdash#13]
No need to make issues - just tick it off when make the PR

Look and feel:
- [ ] make the colour look like Arrow
- [ ] put the "last updated" text somewhere better
- [ ] add colours for infoboxes to make look nice and/or consistent
- [ ]  arrange datatables better so things fit well on screen

Functionality:
- [ ]  make dates be nice human-readable ones
- [ ]  make it so that when we download list of issues we have both the link and the title 
- [ ] Add Stack Overflow and mailing list questions

Code:
- [ ]  using templating so we can expand to other languages
- [ ]  add details of virtual environment to README - Alenka
